version: "3.3"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  app:
    build: .
    command: bundle exec puma -C config/puma/development.rb
    volumes:
      - .:/22_proken
      - public-data:/22_proken/public
      - tmp-data:/22_proken/tmp/sockets/
      - log-data:/22_proken/log
    ports:
      - "3000:3000"
    depends_on:
      - db
  web:
    build:
      context: ./nginx_docker/development/
    volumes:
      - public-data:/22_proken/public
      - tmp-data:/22_proken/tmp/sockets/
    ports:
      - 80:80
    depends_on:
      - app

volumes:
  public-data:
  tmp-data:
  log-data:
