version: "3.3"
services:
  # db:
  #   image: postgres
  #   volumes:
  #     - ./tmp/db:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_PASSWORD: password
  app:
    build: .
    command: bundle exec puma -C config/puma.rb -e production
    volumes:
      - .:/22_PROKEN
      - public-data:/22_PROKEN/public
      - tmp-data:/22_PROKEN/tmp
      - log-data:/22_PROKEN/log
    ports:
      - "3000:3000"
    # depends_on:
    #   - db
  web:
    build:
      context: ./nginx_docker
    volumes:
      - public-data:/22_PROKEN/public
      - tmp-data:/22_PROKEN/tmp
    ports:
      - 80:80
    depends_on:
      - app

volumes:
  public-data:
  tmp-data:
  log-data:
